import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Helmet } from "react-helmet";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="ko">
      <Helmet>
      <head prefix="og: http://ogp.me/ns# fb: http://ogpme/ns/fb# website: http://ogp.me/ns/website#">

      </head>
      </Helmet>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
